### ISSUE TITLE
Tracking issue for WpfMath parity

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#145]
The idea is that CSharpMath should include all functionality in WpfMath but operates cross-platform.

The following numbers are not links to avoid spamming WpfMath. To visit an issue, prepend `https://github.com/ForNeVeR/wpf-math/issues/` before the number.

## Additional proposals (aka Issues)

- [ ] 11: Apply patch Feature: Render geometry & output as SVG
    - We should add documentation on how to use SkiaSharp to output SVGs.
- [ ] 33: Some more project tags
    - This one shold be easy to do
- [ ] 40: MathML input
    - Could port from Typography's MathML implementation
- [ ] 42: Parser for simple arithmetic syntax
    - WIP as the `AngouriUpdate` branch
- [ ] 43: Documentation for contributors
    - We should do this after parser refactors to not waste time and energy
- [ ] 47: Extensible definition dictionary
    - This is equivalent to https://github.com/verybadcat/CSharpMath/pull/143
- [ ] 55: Multiple integrals
    - `\idotsint` should be implemented. For other commands, we should check whether we got the default script style correctly.
- [ ] 61: Implement \\middle delimiter
- [ ] 88: Bar alignment
- ~~96~~: Experimental DirectX renderer
    - Won't do because it is Windows-only, should stay in WpfMath
- ~~115~~: Give a range of source string to Box
    - Won't do because formula editing will operate on MathLists instead on LaTeX strings
- ~~125~~: Make all the Atoms immutable
    - Won't do because MathLists contained in MathAtoms for e.g. scripts and inner lists are inherently mutable
- [ ] 139: \\thinspace exception
    - Not about the exception but about \\thinspace
- [ ] 141: _ doesn't render inside \\text
    - A single _ in \\text renders as underscore as proven by texpaste. Should be done as part of parser refactors.
- [ ] 154: Resource packages for the formula parser
    - Really an extensible parser as in #58.
- [ ] 164: Introduce gold master testing
    - Aka serializing objects to json and comparing to expected json in tests instead of a bunch of `Assert.Equal`. Would need additional discussion on whether to do this.
- [ ] 165: Proposal for color format
- [ ] 171: Parenthesis instead of square brackets
    - Aka \\lbrack and \\rbrack
- [ ] 190: Only a subset of LaTeX formulas supported?
- [ ] 211: Warnings as errors
- [ ] 216: Add commands `\mathrel` and `\joinrel`
- [ ] 239: For size support
- [ ] 262: Add Modulo/remainder operator which is in amsmath

## Implemented WpfMath features

- [ ] \\not

(TBA)

**Comment by charlesroddie** [comment]
I think the title of this should be "interesting WPF-Math proposals", as these are not implemented or even necessarily planned WPF-Math features. WpfMath parity would refer to implemented WpfMath features not supported by CSharpMath.

**Comment by Happypig375** [comment]
Updated section headers to clarify

**Comment by Happypig375** [comment]
Retained as a meta-issue rather than converting to a Discussion. Native sub-issues now connect the concrete CSharpMath parser and command work, so progress is visible without status labels.
